version: "3"
services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'manifold_production'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    networks:
      - network1
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.7
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: 'false'
    networks:
      - network1
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - network1
  api_cable:
    image: manifoldscholar/manifold_api_cable:${MANIFOLD_TAG}
    volumes:
      - ./data/api/public:/opt/manifold/api/public
      - ./data/sockets:/manifold_sockets
    env_file:
      - ./environment/manifold.env
    networks:
      - network1
    command: ["./start-and-run", "bin/cable"]
  api_clockwork:
    image: manifoldscholar/manifold_api_clockwork:${MANIFOLD_TAG}
    volumes:
      - ./data/api/public:/opt/manifold/api/public
      - ./data/sockets:/manifold_sockets
    env_file:
      - ./environment/manifold.env
      - ./environment/rails.env
    networks:
      - network1
    command: ["./start-and-run", "bin/zhong zhong.rb"]
  api_rails:
    image: manifoldscholar/manifold_api_rails:${MANIFOLD_TAG}
    ports:
      - "3020:3020"
    volumes:
      - ./data/api/public:/opt/manifold/api/public
      - ./data/sockets:/manifold_sockets
    env_file:
      - ./environment/manifold.env
    command: ["./start-and-run", "bin/puma -C config/puma.rb"]
    networks:
      - network1
  api_sidekiq:
    image: manifoldscholar/manifold_api_sidekiq:${MANIFOLD_TAG}
    volumes:
      - ./data/api/public:/opt/manifold/api/public
      - ./data/sockets:/manifold_sockets
    env_file:
      - ./environment/manifold.env
    networks:
      - network1
    command: ["./start-and-run", "bin/sidekiq"]
  client:
    image: manifoldscholar/manifold_client:${MANIFOLD_TAG}
    env_file:
      - ./environment/manifold.env
    volumes:
      - ./data/api:/manifold_data
      - ./data/sockets:/manifold_sockets
    command: yarn run start-docker
    networks:
      - network1
  proxy:
    image: manifoldscholar/manifold_proxy:${MANIFOLD_TAG}
    volumes:
      - ./data/nginx/ssl:/etc/nginx/ssl
      - ./data/api/public:/manifold_data/api/public
      - ./data/sockets:/manifold_sockets
    ports:
     - "4000:80"
     - "4001:443"
    command: ["start-nginx"]
    networks:
      - network1
volumes:
  manifold_data:
  manifold_sockets:

networks:
  network1:
